var vs = {
  Aabvere: ["ere vbaa Aabvere"],
  Adavere: ["ere vada Adavere", "erevada - Adavere"],
  Ahnevere: ["ere venha Ahnevere"],
  Alavere: ["ere vala Alavere", "ere valaskala laks Alavere"],
  Alekvere: ["erev kela Alekvere"],
  Allivere: ["ere villa Allivere", "ere villa Allivere"],
  Aluvere: ["ere vula Aluvere"],
  Annikvere: ["erev kinna Annikvere"],
  Annusvere: ["erev sunna Annusvere"],
  Aovere: ["ere voa Aovere"],
  Aruvere: ["ere vura Aruvere", "ere vura Aruvere"],
  Assikvere: ["erev kissa Assikvere"],
  Astivere: ["ere vitsa Astivere", "ere vitsa Astivere"],
  Astuvere: ["erevusta Astuvere"],
  Edivere: ["erev ide Edivere"],
  Eekvere: ["erev kee Eekvere"],
  Eerikvere: ["erev kire Eerikvere"],
  Ellavere: ["erevalle Ellavere"],
  Ihuvere: ["ere vuhi Ihuvere", "ere vuhinaga pagan Ihuvere"],
  Illevere: ["ereville Illevere"],
  Imavere: ["erevami Imavere"],
  Imukvere: ["erevkumi Imukvere"],
  Jellevere: ["ere velle Jellevere", "ere velle Jellevere"],
  Kaavere: ["erev aa Kaavere", "ere va aknaga pagan Kaavere", "ere, va aksakall oli lollakas - Kaavere"],
  Kagavere: ["ere vaga Kagavere", "ere vaga Kagavere"],
  Kagovere: ["erev oga Kagovere", "ere, oga kannas, oo, moos anna - Kagovere"],
  Kaldavere: ["erevad lak Kaldavere"],
  Kallivere: ["ere villa Kallivere", "ere villa Kallivere"],
  Kanavere: ["ere vana Kanavere", "ere vana Kanavere"],
  Karrivere: ["erevirra Karrivere"],
  Kasavere: ["erevasa Kasavere", "ere vasak Kasavere"],
  Kaunivere: ["erevinua Kaunivere"],
  Keravere: ["ere vare Keravere", "ere vare Keravere"],
  Kerevere: ["ere vere Kerevere", "ere vere Kerevere"],
  Kikevere: ["ere veki Kikevere"],
  Kirevere: ["ere veri Kirevere", "ere veri Kirevere"],
  Kirivere: ["ere viri Kirivere"],
  Kiruvere: ["ere vuri Kiruvere"],
  Kodavere: ["ere vado Kodavere"],
  Kostivere: ["ere vits ok Kostivere", "ere vits ok Kostivere"],
  Kullavere: ["ere vallu Kullavere"],
  Kurevere: ["ere veru Kurevere"],
  Kurikvere: ["erev kiru Kurikvere"],
  Külavere: ["ereva lük Külavere"],
  Laanevere: ["ere vena al Laanevere"],
  Lahavere: ["ere vaha Lahavere", "ere vaha Lahavere"],
  Lebavere: ["ere vabe Lebavere", "ere vabe Lebavere"],
  Liiduvere: ["ere vudi il Liiduvere", "ere vudi iluga nagu Liiduvere"],
  Lillevere: ["ere velli Lillevere"],
  Lilovere: ["ere voli Lilovere", "ere voli Lilovere"],
  Liusvere: ["erev suil Liusvere"],
  Lohuvere: ["ere vuho Lohuvere"],
  Loovere: ["ere vool Loovere", "ere vool Loovere"],
  Luhavere: ["ere vahu Luhavere", "ere vahu Luhavere"],
  Lustivere: ["ere vits ul Lustivere", "ere, vits, ulme - uuem Lustivere"],
  Mannavere: ["ere vanna Mannavere"],
  Merevere: ["ere vere Merevere", "ere vere Merevere"],
  Merivere: ["ere vire Merivere", "ere vire Merivere"],
  Metsavere: ["ere vast e Metsavere", "ere vast ema, Metsavere"],
  Mudavere: ["ere vadu Mudavere"],
  Mullavere: ["ere vallu Mullavere"],
  Mõndavere: ["erevad nõm Mõndavere"],
  Niiduvere: ["ere vudin in Niiduvere"],
  Ojavere: ["ereva jo Ojavere"],
  Olukvere: ["erev kulo Olukvere"],
  Paasvere: ["erev saa Paasvere"],
  Pagavere: ["ere vaga Pagavere", "ere vaga Pagavere"],
  Palgivere: ["ere vigla Palgivere", "ere viglapoeta teo Palgivere"],
  Palivere: ["erevila Palivere"],
  Pihuvere: ["ere vuhi Pihuvere"],
  Pikavere: ["ereva ki Pikavere", "ere va kipakast nupp untsaka Pikavere"],
  Pudivere: ["ere vidu Pudivere"],
  Punikvere: ["erev kinu Punikvere"],
  Rabavere: ["ere vaba Rabavere", "ere vaba Rabavere"],
  Rabivere: ["ere viba Rabivere", "ere, viba Rabivere"],
  Rahivere: ["ere viha Rahivere", "ere viha Rahivere"],
  Rannavere: ["erev anna Rannavere"],
  Rehevere: ["erev ehe Rehevere"],
  Rootsivere: ["ere vist oo Rootsivere", "ere vist, oo, Rootsivere"],
  Ruskavere: ["ere vaksu Ruskavere"],
  Ruunavere: ["ere vanu ur Ruunavere", "ere vanu urrav avar Ruunavere"],
  Sirevere: ["ere veri Sirevere", "ere verisena pärisasi, räpane Sirevere", "ere veri Sirevere"],
  Soevere: ["ere veo Soevere", "ere veos Soevere"],
  Soovere: ["ere voo Soovere", "ere voo Soovere"],
  Taevere: ["ere vea Taevere", "ere vea Taevere"],
  Teevere: ["ere vee Teevere", "ere vee Teevere"],
  Tellivere: ["ere ville Tellivere"],
  Tiduvere: ["ere vudi Tiduvere", "ere - vudite? - Tiduvere"],
  Toovere: ["ere voo Toovere", "ere voo Toovere"],
  Tuulivere: ["ere vilu ut Tuulivere"],
  Ulivere: ["ere vilu Ulivere", "ere vilu Ulivere"],
  Univere: ["ere vinu Univere", "ere vinu Univere"],
  Vagivere: ["ere viga Vagivere", "ere viga Vagivere"],
  Vahuvere: ["ere vuha Vahuvere", "ere vuhav Vahuvere"],
  Vanavere: ["ere vana Vanavere", "ere vana Vanavere"],
  Varivere: ["ere virav Varivere"],
  Vassivere: ["ere vissa Vassivere"],
  Venevere: ["ere Venevere", "ere venevaba Venevere", "ere vene, vaba Venevere"],
  Vilivere: ["ere Vilivere", "ere Vilivere", "ere Vilivere"],
  Villevere: ["ere velli Villevere"],
  Viluvere: ["ere vuli Viluvere"],
  Viruvere: ["ere vuri Viruvere"]
};
